Add Peer authorization check to ingress connection
clusterlink-net/clusterlink pull request #156
Opened 2023-11-01 13:15 UTC by kfirtoledo

Add Peer authorization check to ingress connection. 
Small fix to openspeedtest for checking access policy related to source peer.

2023-11-01 13:23 UTC, zivnevo approved these changes
LGTM

2023-11-01 13:31 UTC, orozery requested changes

2023-11-01 13:31 UTC, orozery commented on pkg/controlplane/server/http/authz.go
> +	peer, err := s.cp.AuthorizePeer(r.TLS.PeerCertificates[0].DNSNames)
The purpose of the `Server` struct is just parsing HTTP and passing it on to the lower layer (which is `controlplane::Instance`).
Thus, my view is that the new `AuthorizePeer` function should be merged to `AuthorizeIngress`.

2023-11-01 14:07 UTC, kfirtoledo commented on pkg/controlplane/authz.go
> +	return nil, fmt.Errorf("peer does not exist")
I think we should limit peer access and not allow anyone in the fabric to access this peer, on the other hand, we can say this is the responsibility of the policy engine.

2023-11-01 14:15 UTC, orozery commented on pkg/controlplane/authz.go
> +	return nil, fmt.Errorf("peer does not exist")
Only peers which were signed by the root CA can establish TLS connection.
For more fine-tuned access control we have the policy engine.

2023-11-01 14:17 UTC, orozery commented on pkg/controlplane/authz.go
> +	for _, name := range names {
Our controlplane/dataplane currently verify at startup that the DNS names match the exact format generated by our cl-adm.
Anyhow, I think we talked about requiring the peer CA to be able to sign only DNS names of the form *<peername>.

2023-11-01 20:08 UTC, kfirtoledo commented
@orozery PTAL

2023-11-02 08:29 UTC, orozery approved these changes
I

2023-11-02 08:29 UTC, orozery commented on pkg/controlplane/server/http/authz.go
> +	peerName := r.TLS.PeerCertificates[0].DNSNames[0]
This code can be useful for other purposes.
I think I will open-up a followup PR which moves it to `pkg/certs` (with code moved from `pkg/bootstrap/cert.go`).

2023-11-02 10:20 UTC, merged