Move the utils function for the demos to be under the cluster class.
clusterlink-net/clusterlink pull request #164
Opened 2023-11-05 16:51 UTC by kfirtoledo

Move the utils function for the demos to be under the cluster class,
for reusability, and supports the same demo in the kind and cloud environment.

2023-11-08 08:47 UTC, elevran requested changes
- there seems to be some missing newlines at end of files
- how does this relate to `iperf` changes in #170?

2023-11-08 19:34 UTC, praveingk requested changes

2023-11-08 19:34 UTC, praveingk commented on demos/bookinfo/kind/test.py
> +   print(f"Proctpage1 url: http://{gw1.ip}:30001/productpage")
Typo productpage1

2023-11-09 05:55 UTC, kfirtoledo commented on demos/bookinfo/kind/test.py
> +   print(f"Proctpage1 url: http://{gw1.ip}:30001/productpage")
Done

2023-11-09 06:11 UTC, kfirtoledo commented
@elevran,  The main purpose of this change is that the same test (most of the common parts) will be run in kind and the cloud so that it will be easy to develop the demo in kind and then check it on the cloud.

2023-11-09 06:45 UTC, kfirtoledo commented
@praveingk, @elevran PTAL

2023-11-09 17:24 UTC, praveingk approved these changes

2023-11-10 12:28 UTC, merged