cmd/cl-adm: Add log-level flag
clusterlink-net/clusterlink pull request #167
Opened 2023-11-06 08:29 UTC by kfirtoledo

Add log-level flag to control the level of log messages.

2023-11-06 12:31 UTC, orozery requested changes

2023-11-06 12:31 UTC, orozery commented on tests/e2e/k8s/util/fabric.go
> +	LogLevel string
I don't think we need this.
You can read the "DEBUG" "CICD" env variables at `Fabric::generateK8SYAML`, and pass it on directly to `platform.K8SConfig`.

2023-11-06 12:31 UTC, orozery commented on pkg/bootstrap/platform/config.go
> +	InfoLogLevel = "info"
I don't think we need these definitions. The logging level strings are pretty conventional.
Also, for envoy debugging TRACE level is much more helpful.
So I would use `trace` on `DEBUG=1`.

2023-11-07 12:27 UTC, orozery requested changes

2023-11-07 12:27 UTC, orozery commented on tests/e2e/k8s/util/k8s_yaml.go
> +		if cfg.ExpectLargeDataplaneTraffic || os.Getenv("CICD") == "1" {
```suggestion
		if cfg.ExpectLargeDataplaneTraffic && os.Getenv("CICD") == "1" {
```

2023-11-07 12:27 UTC, orozery commented on tests/e2e/k8s/util/k8s_yaml.go
> +			return "", fmt.Errorf("cannot enable dataplane debug logs: %w", err)
```suggestion
			return "", fmt.Errorf("cannot set dataplane debug level: %w", err)
```

2023-11-07 12:27 UTC, orozery commented on tests/e2e/k8s/util/k8s_yaml.go
> +func dataplaneDebugLogs(yaml, logLevel string) (string, error) {
Can you rename this function to `changeDataplaneDebugLevel`?

2023-11-07 13:13 UTC, kfirtoledo commented
@orozery, PTAL

2023-11-07 13:55 UTC, orozery approved these changes

2023-11-07 15:33 UTC, merged