controlplane: connect enable/disable peer to heartbeat
clusterlink-net/clusterlink pull request #178
Opened 2023-11-12 12:37 UTC by kfirtoledo

Update peer status in policy-engine according to the heartbeat status.

2023-11-12 12:56 UTC, elevran commented on pkg/controlplane/client.go
> +	if !activePrevState && active {
```suggestion
	if active != activePrevState {
	   c.c.peerStatusCallback(active)
	}
```
can be an alternative to L128-134

2023-11-12 12:57 UTC, elevran approved these changes

2023-11-12 12:57 UTC, orozery requested changes

2023-11-12 12:57 UTC, orozery commented on pkg/controlplane/instance.go
> +	client.SetPeerStatusCallback(func(status bool) {
```suggestion
	client.SetPeerStatusCallback(func(isActive bool) {
```

2023-11-12 12:57 UTC, orozery commented on pkg/controlplane/instance.go
> +		if status {
```suggestion
		if isActive {
```

2023-11-12 12:57 UTC, orozery commented on pkg/controlplane/client.go
>  	}
```suggestion
	if activePrevState != active && c.peerStatusCallback != nil {
		c.peerStatusCallback(active)
	}
```

2023-11-12 13:42 UTC, orozery requested changes

2023-11-12 13:42 UTC, orozery commented on pkg/controlplane/client.go
> +		defer c.lock.Unlock()
I don't think that a block helps to make this defer run when you want it.
i.e. https://stackoverflow.com/questions/49456943/why-is-gos-defer-scoped-to-function-not-lexical-enclosure
Let's revert this block, and instead call unlock directly at the end of it.

2023-11-13 07:18 UTC, orozery requested changes

2023-11-13 07:18 UTC, orozery commented on pkg/controlplane/client.go
> +	}
```suggestion
	activePrevState := c.active
	c.active = active
	if active || c.lastSeen.IsZero() {
		c.lastSeen = time.Now()
	}
```

And remove `var activePrevState bool`

2023-11-13 08:29 UTC, orozery approved these changes

2023-11-13 09:33 UTC, merged