tests/e2e/k8s: Add controlplane CRUD test
clusterlink-net/clusterlink pull request #217
Opened 2023-11-23 08:48 UTC by orozery

This PRadds an e2e test which verifies the controlplane CRUD API.
It also includes some refactoring and tweaking of the e2e/k8s suite.

The changes in high-level:
1. Move services out from the suite to a new sub-package.
2. Test service access using nodeport exposing, instead of API server proxy.
3. Let k8s choose the nodeports used by the dataplane services.
4. Get rid of API server raw client. Use clientset for fetching pod logs instead.
5. Add test API which allows stop/start/restart of controlplane/dataplane.

2023-11-26 13:00 UTC, kfirtoledo requested changes

2023-11-26 13:13 UTC, kfirtoledo commented on tests/e2e/k8s/test_basic.go
> -func (s *TestSuite) TestConnectivity() {
I think we still want to keep a simple test for develop

2023-11-26 13:13 UTC, kfirtoledo commented on tests/e2e/k8s/test_basic.go
> +		// delete non-existing binding
This code is repeated for binding, import, peer, etc, can you put in a function?

2023-11-26 13:13 UTC, kfirtoledo commented on tests/e2e/k8s/test_basic.go
> +		//  update access policy
I think it is better to split the e2e policy test from other commands

2023-11-28 07:20 UTC, orozery commented
@kfirtoledo PTAL

2023-11-28 09:41 UTC, kfirtoledo approved these changes

2023-11-28 09:54 UTC, merged