policyengine: Remove ConnectivityPolicy
clusterlink-net/clusterlink pull request #406
Opened 2024-03-17 14:43 UTC by orozery

This PR moves the policyengine to use v1alpha1.AccessPolicy instead of policytypes.ConnectivityPolicy.
The "matches" and "decides" functions are moved to connectivitypdp, as I think it is better to keep `pkg/apis` as short and simple as possible.

2024-03-21 12:12 UTC, zivnevo commented
@orozery , can you please resolve conflicts?

2024-03-25 12:42 UTC, zivnevo requested changes

2024-03-25 12:42 UTC, zivnevo commented on pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
> +		var policy v1alpha1.AccessPolicy
documentation for `addPoliciesFromFile` needs an update

2024-03-25 12:42 UTC, zivnevo commented on pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
> +func TestValidation(t *testing.T) {
This is a duplicate of the test in `accesspolicy_test.go`

2024-03-25 12:49 UTC, orozery commented on pkg/controlplane/authz/manager.go
> +	policyData, err := json.Marshal(accessPolicy)
yes, for LB

2024-03-25 14:29 UTC, zivnevo approved these changes

2024-03-25 16:21 UTC, merged