website: Add iPerf3 tutorial
clusterlink-net/clusterlink pull request #448
Opened 2024-03-27 10:58 UTC by kfirtoledo

Add iperf3 tutorials to documentation.

2024-03-27 12:03 UTC, elevran requested changes
please fix the URLs - everything else is up to your discretion

2024-03-27 12:03 UTC, elevran commented on website/content/en/docs/tutorials/iperf.md
> +    Note: The `PEER_IP` refers to the node IP of the peer Kind Cluster, which assigns the peer YAML file
consider, on the entire document, if using the notice/alert etc shortcodes would be helpful.
You can see examples in peers.md file

2024-03-27 12:03 UTC, elevran commented on website/content/en/docs/tutorials/iperf.md
> +    For more details about policy see [ClusterLink policies](https://github.com/clusterlink-net/clusterlink/docs/concepts/policies.md)
```suggestion
    For more details about policy see [ClusterLink policies](https://clusterlink.net/docs/concepts/policies)
```

2024-03-27 12:40 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +title: iPerf3 Tutorial
In the official website is iPerf
https://iperf.fr/iperf-download.php

2024-03-27 12:49 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +    cp ~/.kube/config $PWD/config-peer1
I added it

2024-03-27 12:51 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +    clusterlink deploy peer --name peer1 --autostart --ingress=NodePort --ingress-port=30443
Yes it start the CRD

2024-03-27 13:00 UTC, kfirtoledo commented on demos/iperf3/testdata/manifests/clusterlink/peer1.yaml
> +      port: 30443
Yes

2024-03-27 13:00 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +    export PEER2_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' peer2-control-plane`
I prefer the hardcoding

2024-03-27 14:01 UTC, elevran approved these changes

2024-03-27 14:01 UTC, elevran commented on website/content/en/docs/tutorials/iperf.md
nit: for users not too familiar with kind, consider adding a note/tip that kind names clusters' context in the kubeconfig with prefix `kind-` so name would be different than specified on the command line?

2024-03-30 16:23 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +    You can run the tutorial in a single terminal and switch access between the clusters using  `kubectl config use-context kind-peerX`.
I did it the same way  as the sites/peers page https://deploy-preview-448--clusterlink-net.netlify.app/docs/concepts/sites/

2024-03-30 16:23 UTC, kfirtoledo commented on demos/iperf3/testdata/manifests/clusterlink/allow-policy.yaml
> +  privileged: false
I will wait for it to merge and fix it.

2024-03-30 16:45 UTC, kfirtoledo commented on website/content/en/docs/tutorials/iperf.md
> +    You can run the tutorial in a single terminal and switch access between the clusters using  `kubectl config use-context kind-peerX`.
I change it to note instead of info.

2024-03-31 22:30 UTC, merged