pkg/api: Cleanup
clusterlink-net/clusterlink pull request #492
Opened 2024-04-03 16:14 UTC by orozery

This PRremoves what's left of pkg/api.
This effect the gwctl/CRUD mode handling of policies.
The access policy API is retained, while the LB policy API is removed, as there are no more demos using it.

2024-04-04 06:20 UTC, kfirtoledo reviewed
LGTM

2024-04-04 10:50 UTC, elevran commented
additional required checks would pass after rebase/update to latest main since the GH actions names on the branch protection rule have automatically changed to reflect the Go1.22 update.

2024-04-09 06:45 UTC, zivnevo commented
@orozery , can you please resolve the conflicts?

2024-04-10 09:14 UTC, zivnevo requested changes
I'm not sure I understand how policy namespace is being handled.
Are we ignoring the namespace specified in the YAML manifest and always use the manager's namespace? Shouldn't we check that they are at least compatible? Is this consistent with the other CRDs?

2024-04-10 09:14 UTC, zivnevo commented on cmd/gwctl/subcommand/policy.go
Need to update command descriptions

2024-04-10 09:41 UTC, orozery commented on pkg/controlplane/store/types.go
> +		Name:             policy.Name,
CRUD mode does not support namespaces.

2024-04-10 10:35 UTC, zivnevo approved these changes

2024-04-10 12:11 UTC, merged